### ISSUE TITLE
The code execution cannot proceed because python37.dll was not found. Reinstalling the program may fix this problem. 

### ISSUE THREAD

**Issue by Hazuki-san** [Pure-Peace/Peace#3]
I doubt this caused by #1, should I install Python 3.7 to resolve this issue?

**Comment by Pure-Peace** [comment]
It seems that it can only be compiled and run locally, due to #1 . Will have to wait for me to fix this...

**Comment by Pure-Peace** [comment]
05095ec639c3fdf75966e4e30fe44283c66d7413 9a979cc8f2953871e0ab190130fd9ebcbd201639 done!
https://github.com/Pure-Peace/simple-rijndael
